<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Account;
use App\Models\Profile;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\Sequence;



class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
     // Seed test user with user id 1
        DB::table('users')->insert([
            'name' => 'Ronald',
            'email' => 'ronald@test.nl',
            'locale' => 'en',
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        ]);
        $testUserId = DB::getPdo()->lastInsertId();
        DB::table('profiles')->insert([
            'user_id' => $testUserId,
            'first_name' => 'Ronald',
            'last_name' => 'Testman',
            'date_of_birth' => '1978-01-01',
            // 'profile_photo_path' => Factory::faker()->imageUrl(128, 128),
            'content' => 'This the test user profile. This use is generated by the UserSeeder to quickly login and test the development site.'
        ]);
         DB::table('accounts')->insert([
            ['name' => 'Personal Account', 'limit_min' => 0, 'limit_max' => 200, 'accountable_type' => 'App\Models\User' , 'accountable_id' => 1, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Then seed factory users
        $usersCount = max((int)$this->command->ask('How many users would you like?', 200), 1);
        User::factory()->count($usersCount)
            ->has(Profile::factory())
            ->has(Account::factory()->state(['name' => 'Personal Account']))
            ->create();
    }
}
