<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Account;
use App\Models\Profile;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\Sequence;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         // Seed Super-Admin with user id 1
        $admin = User::factory()->create([
            'name' => 'Super-Admin',
            'email' => 'admin@admin.com',
            'locale' => 'en',
            'password' => bcrypt('SecurePassword')  // Super-Admin password: 'SecurePassword'
        ]);

        $admin->assignRole('Super-Admin');

        // // TODO: user safer method to find Id!
        // $testUserId = User::where('name', 'Super-Admin')->first();
        // DB::table('profiles')->insert([
        //     'user_id' => $testUserId,
        //     'first_name' => 'Admin',
        //     'last_name' => 'Super-Admin',
        //     'date_of_birth' => '1978-01-01',
        //     'content' => 'This the Super-Admin profile. This user is generated by the UserSeeder to quickly login and test the development site.'
        // ]);

        // TODO: Remove Personal Account for Super-admin user!
        // DB::table('accounts')->insert([
        //    ['name' => 'Personal Account', 'limit_min' => 0, 'limit_max' => 200, 'accountable_type' => 'App\Models\User' , 'accountable_id' => 1, 'created_at' => now(), 'updated_at' => now()],
        // ]);

        // Then seed factory users
        $usersCount = max((int)$this->command->ask('How many users would you like?', 200), 1);
        User::factory()->count($usersCount)
            ->has(Profile::factory())
            ->has(Account::factory()->state(['name' => 'Personal Account']))
            ->create();
    }
}
