window.i18n = {
    "Image": "Afbeelding",
    "Start of publication": "Start publicatie",
    "End of publication": "Einde publicatie",
    "Select language": "Kies taal",
    "Post is saved successfully": "Post is succesvol opgeslagen",
    "Transfer Timebank.cc Hours": "Betaal Timebank.cc uren",
    "Amount": "Aantal",
    "From account": "Vanaf rekening",
    "To account": "Naar rekening",
    "Your transaction history": "Je transactie-overicht",
    "From date": "Vanaf datum",
    "To date": "Tot datum",
    "Date": "Datum",
    "From/to": "Van/naar",
    "Details": "Details",
    "Balance": "Saldo",
    "Commons": "Meent",
    "Yesterday": "Gisteren",
    "Messenger": "Messenger",
    "Chat Messanger": "Chat Messenger",
    "Conversations": "Gesprekken",
    "No conversations": "Geen gesprekken",
    "Pending": "In afwachting",
    "Sent": "Verzonden",
    "Friend Request": "Vriendschapverzoek",
    "Remove friend": "Verwijder vriend",
    "Friend": "Vriend",
    "Connecting": "Verbinden",
    "General Settings": "Algemene instellingen",
    "Drop files to upload": "Sleep bestanden om te uploaden",
    "No Pending Request": "Geen verzoek in afwachting",
    "Search conversations by name": "Zoek gesprekken op naam"
};